name: "blackbox"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Checks the nix formatting.
  nix-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix fmt -- --check ./

  # Check that the flake type-checks.
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check
